version: '3.8'

services:
  cdq-recruitment-app:
    image: 'cdq-recruitment-task:latest'
    build:
      context: .
    container_name: cdq-recruitment-app
    depends_on:
      - cdq-recruitment-app-database
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://cdq-recruitment-app-database:27017/cdq-recruitment-task
    ports:
      - "8105:8105"

  cdq-recruitment-app-database:
    image: mongo
    container_name: cdq-recruitment-app-database
    ports:
      - "27018:27017"